name: Check WeChat Updates

on:
  schedule:
    - cron: '0 * * * *'  # 每小时检查
  workflow_dispatch:      # 支持手动触发

jobs:
  check-updates:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Display current time
        run: |
          echo "Current time: $(date -u '+%Y-%m-%d %H:%M:%S')"
          
      - name: Check for updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python scripts/check_updates.py
