name: Check RSS Updates

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Check RSS updates
        id: check
        run: python scripts/check_updates.py

      - name: Print update status
        run: echo "Has updates - ${{ steps.check.outputs.has_updates }}"