name: Generate RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 需要写入权限来更新RSS文件
      pages: write       # GitHub Pages写入权限
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedgenerator pytz
          
      - name: Generate RSS feed
        run: |
          python scripts/generate_rss.py
        
      - name: Commit and push RSS
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add rss.xml
          git commit -m "Update RSS feed - $(date -u)" || exit 0
          git push
