name: Process New Issues

on:
  issues:
    types: [opened, labeled]  # 添加 labeled 事件触发

jobs:
  process-issue:
    if: contains(github.event.issue.labels.*.name, 'rss-update') && contains(github.event.issue.labels.*.name, 'pending-summary')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Debug Environment
        run: |
          echo "Checking required environment variables..."
          echo "GITHUB_TOKEN exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "SPARK_APP_ID exists: ${{ secrets.SPARK_APP_ID != '' }}"
          echo "SPARK_API_KEY exists: ${{ secrets.SPARK_API_KEY != '' }}"
          echo "SPARK_API_SECRET exists: ${{ secrets.SPARK_API_SECRET != '' }}"
          echo "EMAIL_SENDER exists: ${{ secrets.EMAIL_SENDER != '' }}"
          echo "EMAIL_PASSWORD exists: ${{ secrets.EMAIL_PASSWORD != '' }}"
          echo "EMAIL_RECIPIENT exists: ${{ secrets.EMAIL_RECIPIENT != '' }}"
          echo "Current working directory: $PWD"
          echo "Files in current directory:"
          ls -la
          echo "Files in scripts directory:"
          ls -la scripts/

      - name: Process Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }} 
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python -u scripts/process_issue.py
